<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Design plugin              |
 |                                                                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-design/
*/

$labels = [];
$labels['design'] = 'Design';
$labels['about'] = 'About';
$labels['license'] = 'License';
$labels['csrfinfo'] = 'Read more about CSRF and how we protect you';
$labels['arialabeldesigncontent'] = 'Design content';
